### ISSUE TITLE
Depth file format

### ISSUE THREAD

**Issue by brans-cere** [CanCanZeng/ACMP_colmap#1]
Hi. How to convert the dmb files to depth map? What is this format?

**Comment by CanCanZeng** [comment]
Hi @brans-cere , this depth format is defined in colmap, there is no direct method to convert .bin file to .dmb file or vice versa. But it is very easy if you want to do it.

You just read .bin file, and borrow the code from original ACMP to save it, or vice versa.

https://github.com/colmap/colmap/blob/cf4a39cee879a1c1000bac7f92cdc024c4c4c523/src/mvs/mat.h#L157
use this function to read .bin file
https://github.com/GhiXu/ACMP/blob/604e2347f8a7d302ebaa4cb619b0bf2e87527853/ACMP.cpp#L280
use this function to save .dmb file
